FROM python:3.8-slim-buster

WORKDIR /workspace

RUN pip install --upgrade pip
RUN pip install notebook

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]